<h4>Agregar Club</h2>
<form action="newClub" method="POST" class="row g-3 d-flex justify-content-between align-items-end">
    <div class="col-md-2">
      <label for="nombre" class="form-label">Nombre</label>
      <input type="text" class="form-control" name="nombre" required>
    </div>
    <div class="col-md-2">
      <label for="pais" class="form-label">Pais</label>
      <input type="text" class="form-control" name="pais" required>
    </div>
    <div class="col-md-2">
      <label for="Fecha" class="form-label">Fecha de fundacion</label>
      <input type="date" class="form-control" name="fecha" required>
    </div>
    <div class="col-md-2">
      <label for="titulos" class="form-label">Titulos</label>
      <input type="number" class="form-control" name="titulos" required>
    </div>
    <div class="col-md-2">
      <button type="submit" class="btn btn-primary">Agregar</button>
    </div>
  </form>