<?php require 'templates/layout/header.phtml' ?>
<a id="btn-volver" href="players/" type="button" class='btn btn-details btn-sm ml-auto'></a>

    

<div class="container mt-5">
    <div class="card text-left shadow-sm mx-auto" style="background-color: rgba(255, 255, 255, 0.8); max-width: 600px;">
        <div class="card-header text-center" style="background-color: rgba(0, 0, 0, 0.9); color: white;">
            <h4 class="mb-0" style="font-size: 1.2rem; text-transform: uppercase;">Editar Jugador</h4>
        </div>
        <div class="card-body">
            <form action="editPlayer/<?= $player->id_jugador ?>" method="POST" class="row g-3 d-flex justify-content-center">
                
                <!-- Primera fila -->
                <div class="col-md-6">
                    <label for="nombre" class="form-label">Nombre</label>
                    <input type="text" class="form-control" name="nombre" value='<?= $player->nombre ?>' required>
                </div>
                <div class="col-md-6">
                    <label for="nacionalidad" class="form-label">Pais</label>
                    <input type="text" class="form-control" name="nacionalidad" value='<?= $player->nacionalidad ?>' required>
                </div>

                <!-- Segunda fila -->
                <div class="col-md-6">
                    <label for="posicion" class="form-label">Posicion</label>
                    <input type="text" class="form-control" name="posicion" value='<?= $player->posicion ?>' required>
                </div>
                <div class="col-md-6">
                    <label for="edad" class="form-label">Edad</label>
                    <input type="number" class="form-control" name="edad" value='<?= $player->edad ?>' required>
                </div>
                <div class="col-md-2 text-center">
                 <h3 class="form-label">Club</h3>
                <select name="id_club" id="club" class="form-select">
                <option selected disabled></option>
                <?php foreach ($clubes as $club) {?>
                    <option value="<?= $club->id_club ?>"><?= $club->nombre ?></option>
                <?php } ?>
                </select>
                 </div>

                <!-- Botón de enviar -->
                <div class="col-md-12 d-flex justify-content-center mt-3">
                    <button type="submit" class="btn btn-success">Modificar</button>
                </div>
            </form>
        </div>
    </div>
</div>


<?php require 'templates/layout/footer.phtml' ?>