<?php require 'templates/layout/header.phtml' ?>
<div class="text-center">
            <h1>Bienvenido a la página oficial de Football Center</h1>
            <p>Aqui podra ver la información detallada de jugadores y clubes de futbol.</p>
        </div>
        <div class="secciones mt-5">
            <div class="row">
                <div class="col-md-6">
                    <section class="jugadores bg-light p-3">
                        <h2>Jugadores</h2>
                        <p>Información sobre los jugadores que tenemos registados.</p>
                        <a class="btn btn-primary" href="players">Ver Jugadores</a>
                    </section>
                </div>
                <div class="col-md-6">
                    <section class="clubes bg-light p-3">
                        <h2>Clubes</h2>
                        <p>Información sobre los clubes que tenemos registados.</p>
                        <a class="btn btn-primary" href="clubs">Ver Clubes</a>
                    </section>
                </div>
            </div>
        </div>

<?php require 'templates/layout/footer.phtml' ?>