<?php require 'templates/layout/header.phtml' ?>
<div class="text-center">
<h1 class="text-center fw-bold" style="font-family: 'Arial', sans-serif; font-size: 2.5rem; color: #333; text-shadow: none;">Bienvenido a la página oficial de Zona De Gol</h1>
<p class="text-center" style="font-family: 'Arial', sans-serif; font-size: 1.2rem; color: #555; margin-top: 10px;">Aquí podrá ver la información detallada de jugadores y clubes de fútbol.</p>

 </div>
        <div class="secciones mt-5">
    <div class="row">
        <div class="col-md-6">
            <section class="jugadores bg-black p-4 shadow-sm d-flex flex-column justify-content-center align-items-center" style="height: 320px; border-radius: 10px;">
                <h2 class="fw-bold text-center text-uppercase text-white" style="font-family: 'Arial', sans-serif; font-size: 1.75rem;">Jugadores</h2>
                <p class="text-light text-center mb-4 fw-bold">Información sobre los jugadores que tenemos registrados.</p>
                <a class="btn btn-success btn-lg mt-2" href="players">Ver</a>
            </section>
        </div>
        <div class="col-md-6">
            <section class="clubes bg-black p-4 shadow-sm d-flex flex-column justify-content-center align-items-center" style="height: 320px; border-radius: 10px;">
                <h2 class="fw-bold text-center text-uppercase text-white" style="font-family: 'Arial', sans-serif; font-size: 1.75rem;">Clubes</h2>
                <p class="text-light text-center mb-4 fw-bold">Información sobre los clubes que tenemos registrados.</p>
                <a class="btn btn-success btn-lg mt-2" href="clubs">Ver</a>
            </section>
        </div>
    </div>
</div>




       

   


 




        

<?php require 'templates/layout/footer.phtml' ?>