<?php require 'templates/layout/header.phtml' ?>
<div class="text-center">
            <h1>Bienvenido a la página oficial de Zona De Gol</h1>
            <p>Aqui podra ver la información detallada de jugadores y clubes de futbol.</p>
        </div>
        <div class="secciones mt-5">
            <div class="row">
                <div class="col-md-6">
                    <section class="jugadores bg-light p-3">
                        <h2>Jugadores</h2>
                        <p>Información sobre los jugadores que tenemos registados.</p>
                        <a class="btn btn-primary" href="players">Ver Jugadores</a>
                    </section>
                </div>
                <div class="col-md-6">
                    <section class="clubes bg-light p-3">
                        <h2>Clubes</h2>
                        <p>Información sobre los clubes que tenemos registados.</p>
                        <a class="btn btn-primary" href="clubs">Ver Clubes</a>
                    </section>
                </div>
            </div>
        </div>
        <form class="row g-3">

    <form class="row g-3">
        <div class="col-md-6">
            <label for="inputEmail4" class="form-label">Email</label>
            <input type="email" class="form-control" id="inputEmail4">
        </div>
        <div class="col-md-6">
            <label for="inputPassword4" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputPassword4">
        </div>
  
         <div class="col-12">
            <button type="submit" class="btn btn-primary">Sign in</button>
        </div>
    </form>

        

<?php require 'templates/layout/footer.phtml' ?>