<?php require 'templates/layout/header.phtml' ?>


<a id="btn-volver" href="home/" type="button" class='btn btn-details btn-sm ml-auto'></a>

<ul class="list-group">
<?php foreach($players as $player): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <p class="nombre-jug"><b><?= $player->nombre ?></b></p>
        </div>
        <div class="actions">
            
                <a id="btn-ver" href="viewPlayer/<?= $player->id_jugador ?>" type="button" class='btn btn-details btn-sm ml-auto'>Ver</a> 
                <a id="btn-eliminar" href="deletePlayer/<?= $player->id_jugador ?>" type="button" class='btn btn-details btn-sm ml-auto'></a>
                <a id="btn-editar" href="viewPlayer/<?= $player->id_jugador ?>" type="button" class='btn btn-details btn-sm ml-auto'></a>
           
           
                
        </div>
    </li>
<?php endforeach ?>
</ul>



<?php require 'templates/layout/agregarJugador.phtml' ?>


<?php require 'templates/layout/footer.phtml' ?>
