<?php require 'templates/layout/header.phtml' ?>



<ul class="list-group">
<?php foreach($clubs as $club): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <b><?= $club->nombre ?></b> 
        </div>
        <div class="actions">
            
                <a href="viewClub/<?= $club->id_club ?>" type="button" class='btn btn-details btn-sm ml-auto'>Ver</a> 
           
           
                
        </div>
    </li>
<?php endforeach ?>
</ul>




<?php require 'templates/layout/footer.phtml' ?>
