<?php require 'templates/layout/header.phtml' ?>



<ul class="list-group">
<?php foreach($players as $player): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <b><?= $player->nombre ?></b> 
        </div>
        <div class="actions">
            
                <a href="view/<?= $player->id_jugador ?>" type="button" class='btn btn-details btn-sm ml-auto'>Ver</a> 
           
           
                
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> tareas</small></p>


<?php require 'templates/layout/footer.phtml' ?>
