<?php require 'templates/layout/header.phtml' ?>



<ul class="list-group">
<?php foreach($players as $player): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <b><?= $player->nombre ?></b> | <?=$player->nacionalidad?> | <?= $player->posicion ?>
        </div>
        <div class="actions">
            
                <a href="finalizar/<?= $player->id_jugador ?>" type="button" class='btn btn-success btn-sm ml-auto'>Finalizar</a> 
           
            <a href="eliminar/<?= $player->id_jugador ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> tareas</small></p>


<?php require 'templates/layout/footer.phtml' ?>
