<?php require 'templates/layout/header.phtml' ?>



<section class="vh-50">
  <div class="container-fluid h-100 d-flex justify-content-center align-items-center">
    <div class="row">
      <div class="col-sm-6 text-white">

        <!-- Div gris transparente -->
        <div style="background-color: rgba(36, 34, 34); padding: 20px; border-radius: 8px;">
          <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">

            <form style="width: 60rem;" class="d-flex flex-column align-items-center">

              <!-- Título Zona de Gol -->
              <h1 class="fw-bold mb-4" style="letter-spacing: 3px; font-family: 'Poppins', sans-serif; font-size: 3rem;">
                Zona de Gol
              </h1>

              <div data-mdb-input-init class="form-outline mb-4 w-100">
                <label class="form-label" for="form2Example18">Username</label>
                <input type="email" id="form2Example18" class="form-control form-control-lg" />
              </div>

              <div data-mdb-input-init class="form-outline mb-4 w-100">
                <label class="form-label" for="form2Example28">Password</label>
                <input type="password" id="form2Example28" class="form-control form-control-lg" />
              </div>

              <div class="pt-1 mb-4 w-100 d-flex justify-content-center">
                <button 
                  data-mdb-button-init 
                  data-mdb-ripple-init 
                  style="background-color: rgb(52, 180, 52); color: white; border: none;" 
                  class="btn btn-lg btn-block" 
                  type="button">
                  Login
                </button>
              </div>

            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</section>


<?php require 'templates/layout/footer.phtml' 