<?php require 'templates/layout/header.phtml' ?>



<div class="contenedor-form">
    <div class="login-container">    
      <h2 class="iniciar-sesion">Iniciar Sesión</h2>
        <form class="login-form">
            <div class="input-group">
                <label for="username">Usuario</label>
                <input type="text" id="username" name="username" placeholder="Ingresa tu usuario" required>
            </div>
            <div class="input-group">
                <label for="password">Contraseña</label>
                <input type="password" id="password" name="password" placeholder="Ingresa tu contraseña" required>
            </div>
            <button type="submit">Entrar</button>
            <p class="forgot-password"><a href="#">¿Olvidaste tu contraseña?</a></p>
        </form>
    </div>
</div>



<?php require 'templates/layout/footer.phtml' 