<?php require 'templates/layout/header.phtml' ?>

<a id="btn-volver" href="clubs/" type="button" class='btn btn-details btn-sm ml-auto'></a>

<div class="container mt-5">
    <div class="card text-left shadow-sm mx-auto" style="width: 25rem; height: auto;">
        <div class="card-header text-center" style="background-color: rgba(30, 30, 30, 0.8); color: white;">
            <h2 class="mb-0"><b><?= $club->nombre ?></b></h2>
        </div>
        <div class="card-body d-flex flex-column" style="height: 100%;">
            <ul class="list-group list-group-flush flex-fill">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Pais de origen:</strong> <span><?= $club->pais ?></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Fecha de fundacion:</strong> <span><?= $club->fecha_fundacion ?></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Titulos:</strong> <span><?= $club->titulos ?></span>
                </li>
                
            </ul>
        </div>
    </div>
</div>
<ul class="list-group">
  <?php foreach ($players as $player) { ?>
    <li class="list-group-item">
        <div class="col-md-6">
          <h4><?= $player->nombre ?></h4>
          <p>Club: <?= $player->nombre_club ?></p>
        </div>
    </li>
  <?php } ?>
</ul>









<?php require 'templates/layout/footer.phtml' ?>