<?php require 'templates/layout/header.phtml' ?>

<a id="btn-volver" href="players/" type="button" class='btn btn-details btn-sm ml-auto'></a>

<div class="container mt-5">
    <div class="card text-left shadow-sm mx-auto" style="width: 25rem; height: auto;">
        <div class="card-header text-center" style="background-color: rgba(30, 30, 30, 0.8); color: white;">
            <h2 class="mb-0"><b><?= $player->nombre ?></b></h2>
        </div>
        <div class="card-body d-flex flex-column" style="height: 100%;">
            <ul class="list-group list-group-flush flex-fill">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Nacionalidad:</strong> <span><?= $player->nacionalidad ?></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Posición:</strong> <span><?= $player->posicion ?></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Edad:</strong> <span><?= $player->edad ?></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Club:</strong> <span><?= $player->id_club ?></span>
                </li>
            </ul>
        </div>
    </div>
</div>









<?php require 'templates/layout/footer.phtml' ?>