<?php require 'templates/layout/header.phtml' ?>

<a id="btn-volver" href="clubs/" type="button" class='btn btn-details btn-sm ml-auto'></a>

<ul class="list-group">
      <h2> <b><?= $club->nombre ?></b></h2>
    <li class="list-group-item item-task">
           Pais de origen 🌍 : <b><?= $club->pais ?></b>
     </li>
     <li class="list-group-item item-task">
           Fundacion 📅 :  <b><?= $club->fecha_fundacion ?></b>
     </li> 
     <li class="list-group-item item-task">
           Titulos 🏆 : <b><?= $club->titulos  ?></b>
     </li> 
    
        
    
    
            
</ul>





<?php require 'templates/layout/footer.phtml' ?>