<h4>Agregar Jugador</h2>
<form action="newPlayer" method="POST" class="row g-3 d-flex justify-content-between align-items-end">
    <div class="col-md-2">
      <label for="nombre" class="form-label">Nombre</label>
      <input type="text" class="form-control" name="nombre" required>
    </div>
    <div class="col-md-2">
      <label for="nacionalidad" class="form-label">Nacionalidad</label>
      <input type="text" class="form-control" name="nacionalidad" required>
    </div>
    <div class="col-md-2">
      <label for="posicion" class="form-label">Posicion</label>
      <input type="text" class="form-control" name="posicion" required>
    </div>
    <div class="col-md-2">
      <label for="edad" class="form-label">Edad</label>
      <input type="number" class="form-control" name="edad" required>
    </div>
    <div class="col-md-2">
    <label for="club" class="form-label">Club</label>
    <select name="id_club" id="club" class="form-select">
      <option selected disabled>Seleccionar...</option>
      <?php foreach ($clubs as $club) {?>
        <option value="<?= $club->id_club ?>"><?= $club->nombre ?></option>
      <?php } ?>
    </select>
  </div>  
    <div class="col-md-2">
      <button type="submit" class="btn btn-primary">Agregar</button>
    </div>
    
  </form>