<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Noto+Sans+Cherokee:wght@100..900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <title>Zona de Gol</title>
</head>

<body>
    <!-- main header -->
    <header class="header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-black" style="padding: 13px 50px;"> <!-- Aumenta el padding para mayor altura -->
        <div class="container-fluid">
            <div class="d-flex justify-content-between align-items-center w-100 h-100"> <!-- Centrar verticalmente -->
                <ul class="navbar-nav me-auto">
                  <li class="nav-item">
                     <a href="home" class="nav-link">
                        <div class="logo-header" style="height: 50px;"></div>  <!-- Ajusta la altura según sea necesario -->
                     </a>
                    </li>

                </ul>
                <ul class="navbar-nav mx-auto text-center">
                    <li class="nav-item">
                        <a class="navbar-brand text-white fw-bold zona" href="home" style="font-family: 'Poppins', sans-serif;">Zona De Gol</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <?php if(!isset($_SESSION['USER_ID'])): ?>
                        <li class="nav-item" style="margin-right: 20px;"> <!-- Añadir margen derecho -->
                            <a class="nav-link text-white" href="showLogin">login</a>
                        </li>
                    <?php else: ?>
                        <li class="nav-item" style="margin-right: 20px;"> <!-- Añadir margen derecho -->
                            <a class="nav-link text-white" href="logout">logout</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item"></li>
                    <li class="nav-item"></li>
                </ul>
            </div>
        </div>
    </nav>
</header>






    <main class="container mt-3">